addSbtPlugin("com.lightbend.akka.grpc" % "sbt-akka-grpc"   % "2.3.4")
addSbtPlugin("com.lightbend.sbt"       % "sbt-javaagent"   % "0.1.5")
addSbtPlugin("ch.epfl.scala"           % "sbt-scalafix"    % "0.9.23")
addSbtPlugin("org.scalameta"           % "sbt-scalafmt"    % "2.4.2")
addSbtPlugin("au.com.onegeek"          %% "sbt-dotenv"     % "2.0.117")
addSbtPlugin("org.wartremover"         % "sbt-wartremover" % "2.4.12")
