addSbtPlugin("com.lightbend.akka.grpc" % "sbt-akka-grpc" % "0.8.4")
addSbtPlugin("com.lightbend.sbt" % "sbt-javaagent" % "0.1.5")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"         % "0.9.11")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"         % "2.3.2")
addSbtPlugin("au.com.onegeek"   %% "sbt-dotenv"          % "2.0.117")
addSbtPlugin("org.wartremover"  % "sbt-wartremover" % "2.4.5")
